name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: ''
        command: python3 archery.py
        input: |-
          16 16
          4 -1
          6.1 6.1
        expected-output: |-
          26
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: ''
        command: python3 archery.py
        input: |-
          5.25 3.1
          6.1 0
          -5 -3
        expected-output: |-
          30
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: ''
        command: python3 archery.py
        input: |-
          60.5 0.5
          -10 -60.1
          -30 53.1
        expected-output: |-
          3
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Test 4
      id: test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 4
        setup-command: ''
        command: python3 archery.py
        input: |-
          18.66 13.4
          -30 45
          15 -34
        expected-output: |-
          13
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Test 5
      id: test-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 5
        setup-command: ''
        command: python3 archery.py
        input: |-
          -11 11
          11 -11
          11 11
        expected-output: |-
          24
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
        TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
      with:
        runners: test-1,test-2,test-3,test-4,test-5
